name: Deploy to Azure

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build and Publish
        run: |
          dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'expense-tracker-func'
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_PROFILE }}
